export const positions = [
    "Back-end developer",
    "Full-stack developer",
    "Front-end developer",
    "UI designer",
    "UX designer",
    "SEO manager",
    "Mobile developer",
    "DevOps engineer",
    "Software engineer",
    "Data analyst",
    "Data scientist",
    "Release manager",
    "Web developer",
    "Cloud security specialist",
    "Technical product manager",
    "Product manager",
    "Project manager",
    "CEO",
    "COO",
    "CFO",
    "CTO"
]